# https://github.com/marketplace/actions/labeler
name: 'Pull Request Labeler'
on:
  - pull_request_target

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write

    name: PR Labeler
    runs-on: ubuntu-latest

    steps:
      - name: Labeler
        uses: actions/labeler@v4.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}